#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StevenGuptaStatLoader
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mlbdata2")]
	public partial class glna9svpdbsdp0DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public glna9svpdbsdp0DataContext() : 
				base(global::StevenGuptaStatLoader.Properties.Settings.Default.mlbdata2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public glna9svpdbsdp0DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public glna9svpdbsdp0DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public glna9svpdbsdp0DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public glna9svpdbsdp0DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statSP_PlayerInsert")]
		public int statSP_PlayerInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayerID", DbType="Int")] System.Nullable<int> playerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="VarChar(100)")] string fullName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playerID, fullName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statSP_SelectLoadResult")]
		public int statSP_SelectLoadResult([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameID", DbType="Int")] System.Nullable<int> gameID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchRecords", DbType="Int")] ref System.Nullable<int> pitchRecords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitRecords", DbType="Int")] ref System.Nullable<int> hitRecords, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayRecords", DbType="Int")] ref System.Nullable<int> playRecords)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gameID, pitchRecords, hitRecords, playRecords);
			pitchRecords = ((System.Nullable<int>)(result.GetParameterValue(1)));
			hitRecords = ((System.Nullable<int>)(result.GetParameterValue(2)));
			playRecords = ((System.Nullable<int>)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statSP_HitInsert")]
		public int statSP_HitInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayID", DbType="Int")] System.Nullable<int> playID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataPitchDataID", DbType="Int")] System.Nullable<int> hitDataPitchDataID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataLaunchSpeed", DbType="Decimal(6,3)")] System.Nullable<decimal> hitDataLaunchSpeed, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataLaunchAngle", DbType="Decimal(6,3)")] System.Nullable<decimal> hitDataLaunchAngle, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataTotalDistance", DbType="Decimal(6,3)")] System.Nullable<decimal> hitDataTotalDistance, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataLocation", DbType="Int")] System.Nullable<int> hitDataLocation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataCoordX", DbType="Decimal(7,3)")] System.Nullable<decimal> hitDataCoordX, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HitDataCoordY", DbType="Decimal(7,3)")] System.Nullable<decimal> hitDataCoordY)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playID, hitDataPitchDataID, hitDataLaunchSpeed, hitDataLaunchAngle, hitDataTotalDistance, hitDataLocation, hitDataCoordX, hitDataCoordY);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statSP_PlayInsert")]
		public int statSP_PlayInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameID", DbType="Int")] System.Nullable<int> gameID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayAtBatIndex", DbType="Int")] System.Nullable<int> playAtBatIndex, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BatterID", DbType="Int")] System.Nullable<int> batterID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitcherID", DbType="Int")] System.Nullable<int> pitcherID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayEvent", DbType="VarChar(50)")] string playEvent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayDescription", DbType="VarChar(200)")] string playDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayPitchHand", DbType="VarChar(1)")] string playPitchHand, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayBatHand", DbType="VarChar(1)")] string playBatHand, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayID", DbType="Int")] ref System.Nullable<int> playID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gameID, playAtBatIndex, batterID, pitcherID, playEvent, playDescription, playPitchHand, playBatHand, playID);
			playID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statSP_PitchInsert")]
		public int statSP_PitchInsert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlayID", DbType="Int")] System.Nullable<int> playID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataPitchNumber", DbType="Int")] System.Nullable<int> pitchDataPitchNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataStartSpeed", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataStartSpeed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataPX", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataPX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataPZ", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataPZ, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataX", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataX, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataY", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataBreakAngle", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataBreakAngle, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataBreakLength", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataBreakLength, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataBreakY", DbType="Decimal(6,3)")] System.Nullable<decimal> pitchDataBreakY, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataSpinRate", DbType="Decimal(9,3)")] System.Nullable<decimal> pitchDataSpinRate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataSpinDirection", DbType="Decimal(9,3)")] System.Nullable<decimal> pitchDataSpinDirection, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataCallDescription", DbType="VarChar(200)")] string pitchDataCallDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchTypeCode", DbType="VarChar(10)")] string pitchTypeCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchTypeDescription", DbType="VarChar(100)")] string pitchTypeDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PitchDataPitchID", DbType="Int")] ref System.Nullable<int> pitchDataPitchID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), playID, pitchDataPitchNumber, pitchDataStartSpeed, pitchDataPX, pitchDataPZ, pitchDataX, pitchDataY, pitchDataBreakAngle, pitchDataBreakLength, pitchDataBreakY, pitchDataSpinRate, pitchDataSpinDirection, pitchDataCallDescription, pitchTypeCode, pitchTypeDescription, pitchDataPitchID);
			pitchDataPitchID = ((System.Nullable<int>)(result.GetParameterValue(15)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.statSP_GameInsert")]
		public int statSP_GameInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameID", DbType="Int")] System.Nullable<int> gameID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GameDate", DbType="SmallDateTime")] System.Nullable<System.DateTime> gameDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AwayTeam", DbType="VarChar(50)")] string awayTeam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AwayTeamRuns", DbType="Int")] System.Nullable<int> awayTeamRuns, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AwayTeamHits", DbType="Int")] System.Nullable<int> awayTeamHits, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AwayTeamErrors", DbType="Int")] System.Nullable<int> awayTeamErrors, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HomeTeam", DbType="VarChar(50)")] string homeTeam, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HomeTeamRuns", DbType="Int")] System.Nullable<int> homeTeamRuns, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HomeTeamHits", DbType="Int")] System.Nullable<int> homeTeamHits, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HomeTeamErrors", DbType="Int")] System.Nullable<int> homeTeamErrors, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Venue", DbType="VarChar(50)")] string venue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WeatherTemp", DbType="VarChar(100)")] string weatherTemp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WeatherDesc", DbType="VarChar(100)")] string weatherDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wind", DbType="VarChar(100)")] string wind)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gameID, gameDate, awayTeam, awayTeamRuns, awayTeamHits, awayTeamErrors, homeTeam, homeTeamRuns, homeTeamHits, homeTeamErrors, venue, weatherTemp, weatherDesc, wind);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
